### ISSUE TITLE
How to create a new project?

### ISSUE THREAD

**Issue by RandyRomero** [cryoem-uoft/cryosparc-tools#35]
I am very sorry if the question is dumb, but it is my first time using Cryosparc.
The [documentation](https://tools.cryosparc.com/api/project.html) states that in order to instantiate a Project class one has to use `CryoSPARC.find_project` method. I am wondering, is there a way to create a new project via cryosparc-tools? If no, how does one create a project programmatically?

Thank you in advance

**Comment by nfrasser** [comment]
@RandyRomero it's not documented in the tools docs since it comes from a lower-level API, but you can do this with the `CryoSPARC.cli.create_empty_project` function. Example: 

```py
from cryosparc.tools import CryoSPARC

cs = CryoSPARC(...)
puid = cs.cli.create_empty_project(
    owner_user_id=cs.user_id, 
    project_container_dir="/path/to/projects", 
    title="T20S Proteasome"
)
project = cs.find_project(puid)
```

[Here is the CLI API documentation that documents this function and others](https://guide.cryosparc.com/setup-configuration-and-management/management-and-monitoring/cli#create_empty_project-owner_user_id-str-project_container_dir-str-title-str-desc-optional-str-none-pr).

**Comment by nfrasser** [comment]
We'll include an interface and documentation for this in a future release. Apologies for the confusion!

**Comment by RandyRomero** [comment]
Thank you!
